logging:
  logLevel: info
http:
  port: 3800
rmr:
  port: 3801
  maxMsgSize: 65536
notificationResponseBuffer: 100
bigRedButtonTimeoutSec: 5
maxConnectionAttempts: 3
maxRnibConnectionAttempts: 3
rnibRetryIntervalMs: 10
keepAliveResponseTimeoutMs: 1500
keepAliveDelayMs: 500
routingManagerBaseUrl: http://iltlv740.intl.att.com:8080/ric/v1/handles/v1/
